project:
  type: website
  output-dir: docs  

website:
  title: "Clinician Digital Maturity Assessment"
  navbar:
    logo: figs/digitalhealth.png  
    background: secondary
    right:
      - href: index.qmd
        text: Home
      - href: method.qmd
        text: Method     
      - href: team.qmd
        text: Team             
      - href: https://www.research.net/r/cliniciandigitalsurvey
        text: Survey             

format:
  html:
    theme: zephyr
    css: styles.css
    toc: false

