---
title: "What is the cDMA?"
---

Clinicians suffer every day from slow or broken computers, Electronic Health Record (EHR) downtime, and poor access to vital patient information. These problems, and many others, get in the way of clinical work, and are a **risk to quality and safety of care**. 

The **Clinician Digital Maturity Assessment (cDMA)** was designed by clinicians to measure experiences and pain points of EHR from the shop floor perspective.

The cDMA is designed for any clinical worker (e.g. doctor, nurse, pharmacist, AHP) in **primary care** and **hospitals**.

The results will be used to drive improvement in clinical software and IT.

[Take the cDMA Survey!](https://www.research.net/r/cliniciandigitalsurvey){.btn .btn-primary}

## There are so many surveys, why should I take this one?

Yes, you are right.  There are far too many surveys, and they take far too long. But we would really appreciate it if you did this one. Here is why:

::: {.callout}
(1) **Your voice will be heard**. We are supported by the British Medical Association (BMA) and have direct channels open to the Care Quality Commission (CQC), the Health Safety Services Investigation Body (HSSIB), and to NHS England

(2) It was **designed by 150 of your clinician colleagues** through workshops and a national study to accurately reflect frontline experiences

(3) It takes **8 minutes** (we've tried it!)

(4) The survey is anonymous and **data and results will be available to anyone who wants to analyse it** for free. We hope that this will help you to advocate for change in your local area
:::

## We need you to help spread the word...

We need data to make change happen. That means we need as many of you to take this as possible. If you feel this is important, PLEASE spread the word. On social media, and in your Whatsapp groups!

[How did we design the survey?](method.qmd){.btn .btn-secondary}
[Who created it?](team.qmd){.btn .btn-secondary}
[Take the cDMA Survey!](https://www.research.net/r/cliniciandigitalsurvey){.btn .btn-primary}


## Privacy policy

::: {.callout-important}
We are conducting this survey for the purposes of gathering information about user experiences of IT within the UK Health & Care System. All responses will be anonymous and results will be presented in an aggregated form as to not allow for the identification of any individual. For further information on how we use personal data please visit our [privacy policy](https://www.bma.org.uk/privacy-policy).
:::